project:
  title: "validR"
  output-dir: "docs"

authors:
  - name: H. Wimmer
    affiliation: 
      name: "FH Campus Wien"
      url: "https://www.fh-campuswien.ac.at"
    email: helge.wimmer@fh-campuswien.ac.at

date: 27.Februar 2025
date-format: "DD. MMMM YYYY"
editor: visual
lang: de

format: 
  revealjs:
    chalkboard: true
    multiplex: true
    transition: convex
    background-transition: fade
    footer: "Mathematik 2 - Validierung analytischer Daten"
    logo: logo.png
    slide-number: true
    show-slide-number: print
    incremental: true   
    scrollable: true
    theme: [default, mytheme.scss]


execute: 
  echo: true

